version: "3"

services:
  db:
    image: postgres
    environment: 
      POSTGRES_DB: dbloja
      POSTGRES_USER: userloja 
      POSTGRES_PASSWORD: root
    ports: 
      - 5432:5432
    restart: unless-stopped

  ui: 
    build: ./frontend/
    command: npm start
    ports:
     - 3000:3000
    volumes: 
     - ./src:/usr/app/src
     - ./public:/usr/app/public

         
  api:
    build: ./backend/
    command: sh -c "npm run migrate && npm start"
    ports:
     - 3331:3331
    volumes: 
     - ./src:/usr/app/api
    restart: unless-stopped